/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BarChart: typeof import('./src/components/BarChart.vue')['default']
    Chart: typeof import('./src/components/Chart.vue')['default']
    LineChart: typeof import('./src/components/LineChart.vue')['default']
  }
}
